name: Pull Request Check

on:
  pull_request:
    branches:
      - main
      - uat

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      # This is the only line that changes
      - name: Run Cloudflare-Specific Check Build
        run: npm run open-check
